---
- hosts: cp_nodes
  tasks:
  - name: Initialize the Kubernetes cluster using kubeadm
    command: sudo kubeadm init --config=$HOME/onprem.yaml --skip-phases=addon/kube-proxy

  - name: Initialize the Kubernetes cluster using kubeadm
    command: mkdir -p $HOME/.kube

  - name: Copy admin.conf to .kube/config
    command: sudo -H cp /etc/kubernetes/admin.conf $HOME/.kube/config

  - name: Chown the file to the uid and gid of this user
    command: sudo -H chown 1000:1000 $HOME/.kube/config

    #  - name: Install calico pod network
    #    become: false
    #    command: kubectl apply -f https://docs.projectcalico.org/v3.15/manifests/calico.yaml

    #  - name: Install MetalLB Load Balancer
    #become: false
    #command: kubectl apply -f https://raw.githubusercontent.com/google/metallb/v0.8.3/manifests/metallb.yaml

    #  - name: Install MetalLB Load Balancer Configuration
    #    become: false
    #    command: kubectl apply -f $HOME/metallb-configmap-083.yaml

  - name: Generate join command
    command: kubeadm token create --print-join-command
    register: join_command

  - name: Register join command as a dummy host
    add_host:
      name: "DUMMY_HOST"
      JOINVAR: "{{ join_command.stdout }}"

- hosts: worker_nodes
  become: true
  tasks:
  - name: Record the dummy host join command
    shell: echo -n "{{ hostvars['DUMMY_HOST']['JOINVAR'] }} --cri-socket=/run/containerd/containerd.sock"
    register: join

  - name: Join the node to cluster
    command: "{{join.stdout}}"
